<?php

return [
    'admin_404' => '/templates/admin/images/404.png',
    'userDefault' => false,
    'paginate' => 5,
    'slider_number' => 3,
    'banner' => 4,
    'skip1' => 1,
    'skip2' => 2,
    'skip3' => 3,
  
    'file_upload' => '/templates/upload/',
    'topSell' => 6,
    'rate' => 5,
    'rate_start' => 0,
    'strlimit30' => 30,
    'top' => 3,
    'star5' => 5,
    'star4' => 4,
    'star3' => 3,
    'parent_category' => 0,
    'news_id' => 1,
    'project_id' => 2,
    'num10' => 10,
    'num20' => 20,
    'num30' => 30,
    'grid' => 'grid',
    'list' => 'list',
    'num0' => 0,
    'num1' => 1,
    'paginate_review' => 2,
    'paginate_comment' => 4,
    'paginate_admin' => 10,
    'true' => true,
    'false' => false,
    'direct' => 'direct',
    'status_default' => 0,
    'processing' => 0,
    'delivering' => 1,
    'closed' => 2,
    'folder_css_public' => '/templates/kimoanh/css/',
    'folder_css_admin' => '/templates/admin/css/',
    'folder_image_public' => '/templates/kimoanh/images/',
    'folder_image_admin' => '/templates/admin/images/',
    'folder_js_public' => '/templates/kimoanh/js/',
    'folder_js_admin' => '/templates/admin/js/',
    'limit_top_news' => 5,
    'limit_top_project' => 5,
    'limit_top_library' => 3,
    'paginate_new' => 13,
    'paginate_project' => 5,
    'paginate_project' => 9,
    'paginate_admin' => 10,
    'new_image_default' => '/templates/kimoanh/images/news_default.jpg',
    'project_image_default' => '/templates/kimoanh/images/project_image_default.jpg',
    'page' => [
        'introduce' => 1,
        'project' => 2,
        'news' => 3,
        'library' => 4,
        'contact' => 5,
    ],
    'admin' => [
        'admin' => 1,
        'user' => 0,
    ],
];
